import { createSlice } from '@reduxjs/toolkit';
import { deleteToken,  } from '../../services/localStorageService';


const initialState = {
  user: {
    firstName: "",
    middleName: "",
    lastName: "",
    email: ""
  },
  token: ""
};

export const userDataSlice = createSlice({
  name: 'user',
  initialState: {
    userData: {
      ...initialState
    },
  },
  reducers: {
    setUserData: (state, action) => {
      state.userData = {
        ...state.userData,
        ...action.payload
      }
      console.log(state.userData);
    },
    clearUserData: (state) => {
      //console.log("userdata is about to be cleared")
      state.userData = {
        ...initialState
      }
    },
    logout: (state) => {
      state.userData = {}
      deleteToken()
    }
  },

  //asynchronous reducer logic are handled here using thunks
  extraReducers: {},
});

// exporting actions auto generated by redux-toolkit
export const { setUserData, logout, clearUserData } = userDataSlice.actions;

export default userDataSlice.reducer
